// This file is generated by:
//   npx supabase gen types typescript --local > lib/types/database.ts
// Run after applying migrations to keep in sync with the schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
